import Head from 'next/head'
import '@/styles/globals.css'
import { Header } from '@/components/header'
import { Box } from '@mui/material'
import { Footer } from '@/components/footer'

export default function App({ Component, pageProps }) {
  return (
    <Box display="flex" flexDirection="column" alignItems="center">
      <Head>
        <title>S Systems</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />


        {/* <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&display=swap" rel="stylesheet" /> */}

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;700;800;900&display=swap" rel="stylesheet" />

      </Head>


      <Header />
      <Component {...pageProps} />
      <Footer />
    </Box>
  )
}